name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: List all files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: After checkout
        run: |
          pwd
          ls -a
  