name: PW On Demand Regression Quality Gate
run-name: Run regression tests from ${{ github.ref_name }} on stg ${{ inputs.stage }}

on:
  workflow_dispatch:
    inputs:
      stage:
        description: Type stage number
        required: true
        type: string

jobs:
  run_tests:
    name: Playwright tests run
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.31.0-focal
      options: -m 3g --cpus=2
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn playwright test --grep @finalize-regression --config playwright-regression.config.ts
        env:
          E2E_FINALIZE_PASSWORD: ${{ secrets.USER_PASSWORD }}
          E2E_FINALIZE_WEB_BASE_URL: https://automation.finalize-app-${{ github.event.inputs.stage }}.linksquares.dev
          E2E_GRAPHQL_BASE_URL: https://app.analyze-app-${{ github.event.inputs.stage }}.linksquares.dev/graphql
          E2E_PUBLIC_API_BASE_URL: https://api.analyze-app-${{ github.event.inputs.stage }}.linksquares.dev

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: regression-run-report
          path: e2e/report
          retention-days: 14

      - name: Adding note
        if: always()
        run: echo 'Open index.html from the regression-run-report artifact to read the report.' >> $GITHUB_STEP_SUMMARY