name: PW Run Single Spec
run-name: Run ${{ inputs.specName }} spec on stg ${{ inputs.stage }}

on:
  workflow_dispatch:
    inputs:
      stage:
        description: Type stage number
        required: true
        type: string
      specName:
        type: string
        required: true
        description: Type spec name

jobs:
  run_tests:
    name: Playwright tests run
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.31.0-focal
      options: --ipc=host
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn playwright test ${{ github.event.inputs.specName }} --config playwright-regression.config.ts
        env:
          E2E_FINALIZE_PASSWORD: ${{ secrets.USER_PASSWORD }}
          E2E_FINALIZE_WEB_BASE_URL: https://automation.finalize-app-${{ github.event.inputs.stage }}.linksquares.dev
          E2E_GRAPHQL_BASE_URL: https://app.analyze-app-${{ github.event.inputs.stage }}.linksquares.dev/graphql
          E2E_PUBLIC_API_BASE_URL: https://api.analyze-app-${{ github.event.inputs.stage }}.linksquares.dev

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: single-spec-report
          path: e2e/report

      - name: Adding note
        if: always()
        run: echo 'Open index.html from the single-spec-report artifact to read the report.' >> $GITHUB_STEP_SUMMARY