name: PW Nightly Regression Quality Gate
run-name: Deploy ${{ inputs.feature_branch }} to stg ${{ inputs.stage }} and run regression tests

on:
  schedule:
    - cron: '40 15 * * 1-5'
  workflow_dispatch:
    inputs:
      stage:
        type: boolean
        description: Run ECS Service on Fargate On-Demand. By default its Fargate Spot.
        default: false

jobs:
  feature_branch_deploy:
    name: Trigger stage deploy
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: DmitriiLinkSquares
          repo: actions
          github_token: ${{ secrets.ACCESS_TOKEN }}
          workflow_file_name: test.yml
          ref: ${{ env.feature_branch }}
          wait_interval: 10
          client_payload: '{"service":"${{ env.stage }}"}'

  run_tests:
    needs: feature_branch_deploy
    if: |
      always() &&
      (needs.feature_branch_deploy.result == 'success' || needs.feature_branch_deploy.result == 'skipped')
    name: Playwright tests run
    runs-on: ubuntu-latest
    steps:
      - name: Hey
        run: echo 'Open index.html from the regression-run-report artifact to read the report.' >> $GITHUB_STEP_SUMMARY