name: PW Nightly Regression Quality Gate
run-name: Deploy develop to stg 27 and run regression tests

on:
  workflow_dispatch:
    inputs:
      regression_suite:
        description: Choose regression suite
        required: true
        type: choice
        options:
          - finalize
          - ls-sign

jobs:

  run_tests:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Adding note
        if: always()
        run: |
          echo -e 'Finalize regression status is: **"${{ github.event.inputs.regression_suite == 'finalize' && 'SUCCESS!' }}"** ::rocket:: ..' >> $GITHUB_STEP_SUMMARY

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run Finalize regression
        id: fin_reg
        run: yarn playwright test --grep @finalize-regression --config playwright-regression.config.ts
        env:
          E2E_FINALIZE_PASSWORD: ${{ secrets.USER_PASSWORD }}
          E2E_FINALIZE_WEB_BASE_URL: https://automation.finalize-app-27.linksquares.dev
          E2E_GRAPHQL_BASE_URL: https://app.analyze-app-27.linksquares.dev/graphql
          E2E_PUBLIC_API_BASE_URL: https://api.analyze-app-27.linksquares.dev

      - name: Upload Finalize regression results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: finalize-nightly-regression-report
          path: e2e/report
          retention-days: 14

      - name: Run LS-Sign regression
        id: ls_reg
        if: always()
        run: yarn playwright test --grep @ls-sign-regression --config playwright-regression.config.ts --project="Chrome regression" --no-deps
        env:
          E2E_FINALIZE_PASSWORD: ${{ secrets.USER_PASSWORD }}
          E2E_FINALIZE_WEB_BASE_URL: https://automation.finalize-app-27.linksquares.dev
          E2E_GRAPHQL_BASE_URL: https://app.analyze-app-27.linksquares.dev/graphql
          E2E_PUBLIC_API_BASE_URL: https://api.analyze-app-27.linksquares.dev

      - name: Upload LS-Sign regression results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ls-sign-nightly-regression-report
          path: e2e/report
          retention-days: 14

