name: PW Nightly Regression Quality Gate
run-name: Deploy develop to stg 93 and run regression tests

on:
  schedule:
    - cron: '0 4 * * 1-5'

jobs:
  feature_branch_deploy:
    name: Trigger stage deploy
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: LinkSquares
          repo: parvati
          github_token: ${{ secrets.ACCESS_TOKEN }}
          workflow_file_name: ecs-split-staging.yml
          ref: develop
          wait_interval: 10
          client_payload: '{"service":"93"}'

  run_tests:
    name: Playwright tests run
    runs-on: staging1
    needs: feature_branch_deploy
    container:
      image: mcr.microsoft.com/playwright:v1.31.0-jammy
      options: --ipc=host
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn playwright test --grep @finalize-regression --config playwright-regression.config.ts
        env:
          E2E_FINALIZE_PASSWORD: ${{ secrets.USER_PASSWORD }}
          E2E_FINALIZE_WEB_BASE_URL: https://automation.finalize-app-${{ env.stage }}.linksquares.dev
          E2E_GRAPHQL_BASE_URL: https://app.analyze-app-${{ env.stage }}.linksquares.dev/graphql
          E2E_PUBLIC_API_BASE_URL: https://api.analyze-app-${{ env.stage }}.linksquares.dev

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: nightly-regression-report
          path: e2e/report
          retention-days: 14

      - name: Adding note
        if: always()
        run: echo 'Open index.html from the nightly-regression-report artifact to read the report.' >> $GITHUB_STEP_SUMMARY